baseurl = "/"
languageCode = "en-us"
title = "Student Demands"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

#[[menu.main]]
#    name = "About"
#    url = "/about/"
#[[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/rstudio/blogdown"
#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/rstudio"

[params]
    description = "Database of student activism since January 1, 2020"

    # options for highlight.js (version, additional languages, and theme)
    #highlightjsVersion = "9.12.0"
    #highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #highlightjsLang = ["r", "yaml"]
    #highlightjsTheme = "github"
#
    #MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    #favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

